Instead of copying files in adapters, create hard links where possible
trusterra/paperclip_with_mimemagic_fix pull request #1
Opened 2021-09-23 09:31 UTC by mgutenplan

2021-09-23 09:41 UTC, Mistgun approved these changes

2021-09-24 21:04 UTC, choosen requested changes
please add next fix to this place from master: https://github.com/thoughtbot/paperclip/pull/2532
but in general great finding 👍

2021-09-27 13:28 UTC, mgutenplan commented
@choosen I added you suggestion to PR

2021-09-27 16:02 UTC, choosen approved these changes
LGTM 👍

2021-09-27 20:39 UTC, merged